# Uncomment the next line to define a global platform for your project
 platform :ios, '14.5'

target 'Clinic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Clinic


pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Database'

end
